In [4]:
import pandas as pd

In [32]:
df = pd.read_csv("raw_data.csv")
df2=df.copy()
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [33]:
#show true if null
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [4]:
#To get count of no of missing value in columns
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [36]:
#Drop row having missising value
df.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [35]:
#Fill the give no in missing value
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [37]:
#copy past data to  empty one
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [38]:
#opp th ffill
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [39]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [43]:
df.drop_duplicates(inplace=True)
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [45]:
# apply fun on any columns
df2["tax"] = df2["income"].apply(lambda x:"20%" if x >= 5000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  20%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  20%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [48]:
gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA    NaN  55000.0  20%
1    1      John Doe  29.0     USA    NaN  55000.0  20%
2    2    Jane Smith   NaN  Canada    NaN  62000.0  20%
3    3          Alex   NaN     USA    NaN  47000.0  20%
4    4  Maria Garcia  34.0   Spain    NaN      NaN  10%
5    5        Li Wei  27.0   China    NaN  51000.0  20%
6    6           NaN  45.0   India    NaN  73000.0  20%
7    7    Ahmed Khan  38.0     NaN    NaN  68000.0  20%
8    8    Rachel Lee  29.0     USA    NaN  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico    NaN  45000.0  20%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [56]:
df3=df.copy()
neword = [col for col in df3.columns if col != id] + ["id"]
print(neword)
df3[neword]

['id', 'name', 'age', 'country', 'gender', 'income', 'id']

    id          name   age country   gender   income  id
0    1      John Doe  29.0     USA     Male  55000.0   1
2    2    Jane Smith   NaN  Canada   Female  62000.0   2
3    3          Alex   NaN     USA  Unknown  47000.0   3
4    4  Maria Garcia  34.0   Spain   Female      NaN   4
5    5        Li Wei  27.0   China     Male  51000.0   5
6    6           NaN  45.0   India   Female  73000.0   6
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   7
8    8    Rachel Lee  29.0     USA   Female  62000.0   8
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10  10   Emily Davis  31.0     USA      NaN  58000.0  10