In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("raw_data.csv")
df2=df.copy()
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
df3=df.copy()
neword = [col for col in df3.columns if col != "id"] + ["id"]
print(neword)
df3[neword]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [7]:
gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income
0    1      John Doe  29.0     USA      M  55000.0
1    1      John Doe  29.0     USA      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN     USA      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0     USA      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0

In [27]:
df2=df.copy()
df2=df2.drop_duplicates()
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2.to_csv("Sorteddata.csv")
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [30]:
df2.groupby("country")["income"].mean()
df2.groupby("country")["income"].max()
df2.groupby("country")["income"].min()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       47000.0
Name: income, dtype: float64

In [32]:
df.groupby("country")["income"].agg(avg_sal = "mean",max_sal="max",min_sal="min")

         avg_sal  max_sal  min_sal
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  62000.0  47000.0

In [44]:
#melt and pivot
df=pd.DataFrame({
    "country":["usa","usa","india","india"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22]
}
               )
melted_data=df.melt(
    id_vars = ["country","year"],
    value_vars=["sales","profit"],
    var_name = "metrics",
    value_name="values"
)
melted_data

  country  year metrics  values
0     usa  2020   sales     100
1     usa  2021   sales     120
2   india  2020   sales      90
3   india  2021   sales     110
4     usa  2020  profit      20
5     usa  2021  profit      25
6   india  2020  profit      18
7   india  2021  profit      22

In [46]:
orignal = melted_data.pivot(
    index = ["country","year"],
    columns = "metrics",
    values="values"
)
orignal

metrics       profit  sales
country year
india   2020      18     90
        2021      22    110
usa     2020      20    100
        2021      25    120